server:
  port: 8110 #服务端口

spring:
  profiles:
    active: dev #环境配置
  application:
    name: service-core #服务名
  datasource: #mysql数据库连接
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql1234
    url: jdbc:mysql://localhost:3306/hhjr_core?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true

  redis:
    host: 192.168.1.94
    port: 6379
    database: 0
    password: 123456 #默认为空
    timeout: 3000ms #最大等待时间，超过则抛出异常，否则请求一直等待
    lettuce:
      pool:
        max-active: 20 #最大连接数，负值表示没有限制，默认8
        max-wait: -1  #最大阻塞等待时间，负值表示没有限制，默认-1
        max-idle: 8  #最大空闲连接，默认8
        min-idle: 0  #最小空闲连接，默认0

mybatis-plus: #mybatis plus
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #mybatis日志输出
  mapper-locations: classpath:com/hui/hhjr/core/mapper/xml/*.xml #mybatis xml文件位置

# 设置日志级别
#logging:
#  level:
#    root: ERROR